apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
  namespace: default
spec:
  containers:
  - name: debug-container
    image: busybox
    command: ["/bin/sh", "-c", "sleep 3600"]
    volumeMounts:
    - mountPath: /mnt/data
      name: debug-volume
  volumes:
  - name: debug-volume
    persistentVolumeClaim:
      claimName: datadir-proglog-0
  restartPolicy: Never