apiVersion: v1
kind: Service
metadata:
  name: proglog-nodeport
  namespace: default
  labels:
    app.kubernetes.io/instance: proglog
    app.kubernetes.io/name: proglog
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: proglog
  ports:
    - protocol: TCP
      port: 8400
      targetPort: 8400
      nodePort: 30000